services:
  db-main:
    image: postgres:16-alpine
    container_name: db-main
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=main_db
    volumes:
      - db_main_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d main_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-users:
    image: postgres:16-alpine
    container_name: db-users
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=users_db
    volumes:
      - db_users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - ROOT_PATH=
    volumes:
      - ./backend/src:/app/src
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/migrations:/app/migrations
    depends_on:
      db-main:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal
    ports:
      - "8001:8000"

  users-api:
    build: ./users_service
    container_name: users-api
    volumes:
      - ./users_service/src:/app/src
      - ./users_service/alembic.ini:/app/alembic.ini
      - ./users_service/migrations:/app/migrations
    env_file:
      - ./users_service/.env
    depends_on:
      db-users:
        condition: service_healthy
    networks:
      - internal

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - users-api
    ports:
      - "80:80"
    networks:
      - internal

  redis:
    ports:
      - "6379:6379"
    image: redis:7-alpine
    container_name: redis
    networks:
      - internal

  push-notificator:
    image: ghcr.io/ayusavin/push-notification-playground:1.0.0
    container_name: push-notificator
    ports:
      - "8000:8000"
    networks:
      - internal

  worker:
    volumes:
      - ./worker:/app
    build: ./worker
    container_name: worker
    env_file:
      - ./worker/.env
    depends_on:
      - redis
      - push-notificator
      - db-users
      - db-main
      - backend
    networks:
      - internal

  # DLQ Worker - обработка неудачных задач
  dlq-worker:
    volumes:
      - ./worker:/app
    build: ./worker
    container_name: dlq-worker
    env_file:
      - ./worker/.env
    command: ["celery", "-A", "services.RunTasks", "worker", "--loglevel=info", "-Q", "dlq"]
    depends_on:
      - redis
      - backend
      - db-main
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_main_data:
  db_users_data: